//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubStringOccuranceConsumer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOccuranceService")]
    public interface IOccuranceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceService/GetOccurance", ReplyAction="http://tempuri.org/IOccuranceService/GetOccuranceResponse")]
        int GetOccurance(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceService/GetOccurance", ReplyAction="http://tempuri.org/IOccuranceService/GetOccuranceResponse")]
        System.Threading.Tasks.Task<int> GetOccuranceAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOccuranceServiceChannel : SubStringOccuranceConsumer.ServiceReference1.IOccuranceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OccuranceServiceClient : System.ServiceModel.ClientBase<SubStringOccuranceConsumer.ServiceReference1.IOccuranceService>, SubStringOccuranceConsumer.ServiceReference1.IOccuranceService {
        
        public OccuranceServiceClient() {
        }
        
        public OccuranceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OccuranceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OccuranceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OccuranceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetOccurance(string first, string second) {
            return base.Channel.GetOccurance(first, second);
        }
        
        public System.Threading.Tasks.Task<int> GetOccuranceAsync(string first, string second) {
            return base.Channel.GetOccuranceAsync(first, second);
        }
    }
}
